displayName=Bronzeman Unleashed
author=Elertan
support=
description=Ironman without the chores. Flexible rule sets for solo play or shared group progression.
tags=gamemode,trade,restrict,group,bronzeman
plugins=com.elertan.BUPlugin
