package com.elertan;

import com.google.common.collect.ImmutableSet;
import java.util.Set;

/**
 * Items that must never count as unlocks.
 */
public final class ExcludedItemIds {

    public static final Set<Integer> IDS = ImmutableSet.of(
        // Minigame items: copies that only exist inside Last Man Standing and Pete Kayer's Challenges,
        // they cannot be taken out of the minigame.
        // Generated from net.runelite.api.gameval.ItemID (BR_* and PVPTUT_COMBO_EATING_SUPPLY_CRATE), rev241
        // Excludes the BR_* rewards from the LMS reward shop, which are kept outside the minigame:
        // Deadman's chest/legs/cape (24189-24191) and Victor's capes (24207-24215, 24520)
        20390, // Shark (BR_SHARK)
        20391, // Null (BR_SWORDFISH)
        20392, // Null (BR_BASS)
        20393, // Prayer potion(4) (BR_PRAYER4)
        20394, // Prayer potion(3) (BR_PRAYER3)
        20395, // Prayer potion(2) (BR_PRAYER2)
        20396, // Prayer potion(1) (BR_PRAYER1)
        20397, // Spear (BR_HALBERD)
        20398, // Null (BR_MITHRIL_SCIMITAR)
        20399, // Null (BR_WILLOW_BOW)
        20400, // Null (BR_ADAMANT_SCIMITAR)
        20401, // Yew shortbow (BR_YEW_BOW)
        20402, // Rune scimitar (BR_RUNE_SCIMITAR)
        20403, // Maple shortbow (BR_MAPLE_BOW)
        20404, // Null (BR_AIR_STAFF)
        20405, // Abyssal whip (BR_ABYSSAL_WHIP)
        20406, // Dragon scimitar (BR_DRAGON_SCIMITAR)
        20407, // Dragon dagger (BR_DRAGON_DAGGER)
        20408, // Dark bow (BR_DARKBOW)
        20409, // Null (BR_MITHRIL_PLATEBODY)
        20410, // Null (BR_MITHRIL_PLATELEGS)
        20411, // Null (BR_GREENDHIDE_BODY)
        20412, // Null (BR_GREENDHIDE_CHAPS)
        20413, // Null (BR_MOONCLAN_BODY)
        20414, // Null (BR_MOONCLAN_LEGS)
        20415, // Adamant platebody (BR_ADAMANT_PLATEBODY)
        20416, // Adamant platelegs (BR_ADAMANT_PLATELEGS)
        20417, // Blue d'hide body (BR_BLUEDHIDE_BODY)
        20418, // Blue d'hide chaps (BR_BLUEDHIDE_CHAPS)
        20419, // Null (BR_XERIC_BODY)
        20420, // Null (BR_XERIC_LEGS)
        20421, // Rune platebody (BR_RUNE_PLATEBODY)
        20422, // Rune platelegs (BR_RUNE_PLATELEGS)
        20423, // Black d'hide body (BR_BLACKDHIDE_BODY)
        20424, // Black d'hide chaps (BR_BLACKDHIDE_CHAPS)
        20425, // Mystic robe top (BR_MYSTIC_BODY)
        20426, // Mystic robe bottom (BR_MYSTIC_LEGS)
        20427, // Null (BR_DRAGON_HELM)
        20428, // Dragon chainbody (BR_DRAGON_BODY)
        20429, // Dragon platelegs (BR_DRAGON_LEGS)
        20430, // Ancient magicks tablet (BR_TABLET_ANCIENTS)
        20431, // Ancient staff (BR_ANCIENT_STAFF)
        20523, // Catalytic rune pack (BR_CATALYTIC_RUNE_PACK)
        20524, // Elemental rune pack (BR_ELEMENTAL_RUNE_PACK)
        20525, // Adamant arrow pack (BR_ADAMANT_ARROW_PACK)
        20526, // Bloody key (BR_BLOODY_KEY)
        20527, // Survival token (BR_TOKEN)
        20528, // Survival token (BR_TOKEN_2)
        20529, // Survival token (BR_TOKEN_3)
        20530, // Survival token (BR_TOKEN_4)
        20531, // Survival token (BR_TOKEN_5)
        20547, // Monkfish (BR_MONKFISH)
        20548, // Super energy(4) (BR_ENERGY4)
        20549, // Super energy(3) (BR_ENERGY3)
        20550, // Super energy(2) (BR_ENERGY2)
        20551, // Super energy(1) (BR_ENERGY1)
        20552, // Rune battleaxe (BR_RUNE_BATTLEAXE)
        20553, // Beginner wand (BR_BEGINNER_WAND)
        20554, // Toktz-xil-ak (BR_OBSIDIAN_SWORD)
        20555, // Rune 2h sword (BR_RUNE_2H)
        20556, // Apprentice wand (BR_APPRENTICE_WAND)
        20557, // Granite maul (BR_GRANITE_MAUL)
        20558, // Magic shortbow (BR_MAGIC_BOW)
        20559, // Dragon 2h sword (BR_DRAGON_2H)
        20560, // Master wand (BR_MASTER_WAND)
        20561, // Adamant full helm (BR_ADAMANT_HELM)
        20562, // Mystic hat (BR_MYSTIC_HAT)
        20563, // Proselyte sallet (BR_PROSELYTE_HELM)
        20564, // Proselyte hauberk (BR_PROSELYTE_BODY)
        20565, // Proselyte cuisse (BR_PROSELYTE_LEGS)
        20566, // Red d'hide body (BR_REDDHIDE_BODY)
        20567, // Red d'hide chaps (BR_REDDHIDE_CHAPS)
        20568, // Splitbark helm (BR_SPLITBARK_HELM)
        20569, // Null (BR_SPLITBARK_BODY)
        20570, // Null (BR_SPLITBARK_LEGS)
        20571, // Warrior helm (BR_WARRIOR_HELM)
        20572, // Archer helm (BR_ARCHER_HELM)
        20573, // Farseer helm (BR_FARSEER_HELM)
        20574, // Infinity top (BR_INFINITY_BODY)
        20575, // Infinity bottoms (BR_INFINITY_LEGS)
        20576, // 3rd Age robe top (BR_3A_MAGE_BODY)
        20577, // 3rd Age robe (BR_3A_MAGE_LEGS)
        20578, // Climbing boots (BR_CLIMBING_BOOTS)
        20579, // Mystic boots (BR_MYSTIC_BOOTS)
        20580, // Snakeskin boots (BR_SNAKESKIN_BOOTS)
        20581, // Mithril gloves (BR_MITHRIL_GLOVES)
        20582, // Adamant gloves (BR_ADAMANT_GLOVES)
        20583, // Rune gloves (BR_RUNE_GLOVES)
        20584, // Amulet of accuracy (BR_AMULET_OF_ACCURACY)
        20585, // Amulet of power (BR_AMULET_OF_POWER)
        20586, // Amulet of glory (BR_AMULET_OF_GLORY)
        20587, // Rope (BR_ROPE)
        20593, // Armadyl godsword (BR_AGS)
        20598, // Ahrim's robetop (BR_AHRIM_BODY)
        20599, // Ahrim's robeskirt (BR_AHRIM_LEGS)
        20607, // Rune arrow pack (BR_RUNE_ARROW_PACK)
        20608, // Bloodier key (BR_BLOODIER_KEY)
        20784, // Dragon claws (BR_DRAGON_CLAWS)
        20785, // Dragon warhammer (BR_DRAGON_WARHAMMER)
        21205, // Elder maul (BR_ELDER_MAUL)
        21206, // Dragon sword (BR_DRAGON_SWORD)
        21207, // Dragon thrownaxe (BR_DRAGON_THROWNAXE)
        23533, // Cooked karambwan (BR_TBWT_COOKED_KARAMBWAN)
        23543, // Super combat potion(4) (BR_4DOSE2COMBAT)
        23545, // Super combat potion(3) (BR_3DOSE2COMBAT)
        23547, // Super combat potion(2) (BR_2DOSE2COMBAT)
        23549, // Super combat potion(1) (BR_1DOSE2COMBAT)
        23551, // Ranging potion(4) (BR_4DOSERANGERSPOTION)
        23553, // Ranging potion(3) (BR_3DOSERANGERSPOTION)
        23555, // Ranging potion(2) (BR_2DOSERANGERSPOTION)
        23557, // Ranging potion(1) (BR_1DOSERANGERSPOTION)
        23559, // Sanfew serum(4) (BR_SANFEW_SALVE_4_DOSE)
        23561, // Sanfew serum(3) (BR_SANFEW_SALVE_3_DOSE)
        23563, // Sanfew serum(2) (BR_SANFEW_SALVE_2_DOSE)
        23565, // Sanfew serum(1) (BR_SANFEW_SALVE_1_DOSE)
        23567, // Super restore(4) (BR_4DOSE2RESTORE)
        23569, // Super restore(3) (BR_3DOSE2RESTORE)
        23571, // Super restore(2) (BR_2DOSE2RESTORE)
        23573, // Super restore(1) (BR_1DOSE2RESTORE)
        23575, // Saradomin brew(4) (BR_4DOSEPOTIONOFSARADOMIN)
        23577, // Saradomin brew(3) (BR_3DOSEPOTIONOFSARADOMIN)
        23579, // Saradomin brew(2) (BR_2DOSEPOTIONOFSARADOMIN)
        23581, // Saradomin brew(1) (BR_1DOSEPOTIONOFSARADOMIN)
        23583, // Stamina potion(4) (BR_4DOSESTAMINA)
        23585, // Stamina potion(3) (BR_3DOSESTAMINA)
        23587, // Stamina potion(2) (BR_2DOSESTAMINA)
        23589, // Stamina potion(1) (BR_1DOSESTAMINA)
        23591, // Helm of Neitiznot (BR_FRIS_KINGLY_HELM)
        23593, // Barrows gloves (BR_HUNDRED_GAUNTLETS_LEVEL_10)
        23595, // Berserker ring (i) (BR_BERZERKER_RING)
        23597, // Dragon defender (BR_DRAGON_PARRYINGDAGGER)
        23599, // Spirit shield (BR_SPIRIT_SHIELD)
        23601, // Rune crossbow (BR_XBOWS_CROSSBOW_RUNITE)
        23603, // Imbued Guthix cape (BR_MA2_GUTHIX_CAPE)
        23605, // Imbued Zamorak cape (BR_MA2_ZAMORAK_CAPE)
        23607, // Imbued Saradomin cape (BR_MA2_SARADOMIN_CAPE)
        23609, // Ava's accumulator (BR_ANMA_50_REWARD)
        23611, // Armadyl crossbow (BR_ACB)
        23613, // Staff of the Dead (BR_SOTD)
        23615, // Vesta's longsword (BR_VESTAS_LONGSWORD)
        23617, // Zuriel's staff (BR_ZURIELS_STAFF)
        23619, // Morrigan's javelin (BR_MORRIGANS_JAVELIN)
        23620, // Statius's warhammer (BR_STATIUS_WARHAMMER)
        23622, // Infernal cape (BR_INFERNAL_CAPE)
        23624, // Seers ring (i) (BR_NZONE_SEER_RING)
        23626, // Kodai wand (BR_KODAI_WAND)
        23628, // Ghrazi rapier (BR_GHRAZI_RAPIER)
        23630, // Heavy ballista (BR_HEAVY_BALLISTA)
        23632, // Karil's leathertop (BR_BARROWS_KARIL_BODY)
        23633, // Dharok's platelegs (BR_BARROWS_DHAROK_LEGS)
        23634, // Torag's platelegs (BR_BARROWS_TORAG_LEGS)
        23635, // Verac's plateskirt (BR_BARROWS_VERAC_LEGS)
        23636, // Verac's helm (BR_BARROWS_VERAC_HEAD)
        23637, // Torag's helm (BR_BARROWS_TORAG_HEAD)
        23638, // Guthan's helm (BR_BARROWS_GUTHAN_HEAD)
        23639, // Dharok's helm (BR_BARROWS_DHAROK_HEAD)
        23640, // Amulet of fury (BR_ENCHANTED_ONYX_AMULET)
        23642, // Blessed spirit shield (BR_BLESSED_SPIRIT_SHIELD)
        23644, // Eternal boots (BR_ETERNAL_BOOTS)
        23646, // Bandos tassets (BR_BANDOS_SKIRT)
        23648, // Dragon javelin (BR_DRAGON_JAVELIN)
        23649, // Diamond bolts (e) (BR_DSTONE_BOLTS_E)
        23650, // Rune pouch (BR_RUNE_REPLACEMENT)
        23652, // Mage's book (BR_MAGESBOOK)
        23653, // Ahrim's staff (BR_BARROWS_AHRIM_WEAPON)
        23654, // Occult necklace (BR_OCCULT_NECKLACE)
        24534, // Mithril seeds (BR_MITHRIL_SEED)
        25515, // Dharok's platebody (BR_BARROWS_DHAROK_BODY)
        25516, // Dharok's greataxe (BR_BARROWS_DHAROK_WEAPON)
        25517, // Volatile Nightmare staff (BR_NIGHTMARE_STAFF_VOLATILE)
        25518, // Ancestral hat (BR_ANCESTRAL_HAT)
        27157, // Dragon knife (BR_DRAGON_KNIFE)
        27158, // Mystic robe top (dark) (BR_MYSTIC_BODY_DARK)
        27159, // Mystic robe bottom (dark) (BR_MYSTIC_LEGS_DARK)
        27160, // Mystic robe top (light) (BR_MYSTIC_BODY_LIGHT)
        27161, // Mystic robe bottom (light) (BR_MYSTIC_LEGS_LIGHT)
        27162, // Wizard boots (BR_WIZARD_BOOTS)
        27163, // Guthix halo (BR_GUTHIX_HALO)
        27164, // Zamorak halo (BR_ZAMORAK_HALO)
        27165, // Saradomin halo (BR_SARADOMIN_HALO)
        27166, // Ghostly hood (BR_SECRET_GHOST_HAT)
        27167, // Ghostly robe (BR_SECRET_GHOST_TOP)
        27168, // Ghostly robe (BR_SECRET_GHOST_BOTTOM)
        27169, // Berserker helm (BR_BERSERKER_HELM)
        27170, // Infinity boots (BR_INFINITY_BOOTS)
        27171, // Tormented bracelet (BR_TORMENTED_BRACELET)
        27172, // Necklace of anguish (BR_ANGUISH_NECKLACE)
        27173, // Amulet of torture (BR_TORTURE_AMULET)
        27174, // Elder chaos top (BR_ELDERCHAOS_TOP)
        27175, // Elder chaos robe (BR_ELDERCHAOS_BOTTOM)
        27176, // Elder chaos hood (BR_ELDERCHAOS_HOOD)
        27177, // Fremennik kilt (BR_FREMENNIK_KILT)
        27178, // Spiked manacles (BR_SPIKED_MANACLES)
        27179, // Rangers' tunic (BR_RANGER_TUNIC)
        27180, // Guthix chaps (BR_GUTHIX_CHAPS)
        27181, // Zamorak chaps (BR_ZAMORAK_CHAPS)
        27182, // Saradomin chaps (BR_SARADOMIN_CHAPS)
        27183, // 3rd Age mage hat (BR_3A_MAGE_HAT)
        27184, // Ancient godsword (BR_ANCIENT_GODSWORD)
        27185, // Rune defender (BR_RUNE_PARRYINGDAGGER)
        27186, // Zaryte crossbow (BR_ZARYTE_XBOW)
        27187, // Bow of Faerdhinen (c) (BR_BOW_OF_FAERDHINEN)
        27188, // Light ballista (BR_LIGHT_BALLISTA)
        27189, // Verac's flail (BR_BARROWS_VERAC_WEAPON)
        27190, // Verac's brassard (BR_BARROWS_VERAC_BODY)
        27191, // Unholy book (BR_ZAMORAKBOOK)
        27192, // Opal dragon bolts (e) (BR_DRAGON_BOLTS_ENCHANTED_OPAL)
        27193, // Ancestral robe top (BR_ANCESTRAL_TOP)
        27194, // Ancestral robe bottom (BR_ANCESTRAL_BOTTOM)
        27195, // Inquisitor's great helm (BR_INQUISITORS_HELM)
        27196, // Inquisitor's hauberk (BR_INQUISITORS_BODY)
        27197, // Inquisitor's plateskirt (BR_INQUISITORS_SKIRT)
        27198, // Inquisitor's mace (BR_INQUISITORS_MACE)
        27199, // 3rd Age range top (BR_3A_RANGER_TORSO)
        27200, // 3rd Age range legs (BR_3A_RANGER_LEGS)
        27201, // 3rd Age range coif (BR_3A_RANGER_COIF)
        27358, // Tome of Fire (BR_TOME_OF_FIRE)
        27869, // Voidwaker (BR_VOIDWAKER)
        27870, // Lightbearer (BR_LIGHTBEARER)
        29840, // Eclipse Moon chestplate (BR_ECLIPSE_MOON_CHESTPLATE)
        29841, // Eclipse Moon tassets (BR_ECLIPSE_MOON_TASSETS)
        29842, // Eclipse Moon helm (BR_ECLIPSE_MOON_HELM)
        29843, // Blue Moon chestplate (BR_FROST_MOON_CHESTPLATE)
        29844, // Blue Moon tassets (BR_FROST_MOON_TASSETS)
        29845, // Blue Moon helm (BR_FROST_MOON_HELM)
        29846, // Blood Moon chestplate (BR_BLOOD_MOON_CHESTPLATE)
        29847, // Blood Moon tassets (BR_BLOOD_MOON_TASSETS)
        29848, // Blood Moon helm (BR_BLOOD_MOON_HELM)
        29849, // Blue Moon spear (BR_FROSTMOON_SPEAR)
        29850, // Dual macuahuitl (BR_DUAL_MACUAHUITL)
        29851, // Eclipse atlatl (BR_ECLIPSE_ATLATL)
        29852, // Atlatl dart (BR_ATLATL_DART)
        33166, // Crystal body (BR_CRYSTAL_CHESTPLATE)
        33168, // Crystal legs (BR_CRYSTAL_PLATELEGS)
        33170, // Crystal helm (BR_CRYSTAL_HELMET)
        33172, // Avernic treads (max) (BR_AVERNIC_TREADS)
        33174, // Osmumten's fang (BR_OSMUMTENS_FANG)
        33176, // Elidinis' ward (f) (BR_ELIDINIS_WARD_FORTIFIED)
        33178, // Noxious halberd (BR_NOXIOUS_HALBERD)
        33180, // Magus ring (BR_MAGUS_RING)
        33182, // Ultor ring (BR_ULTOR_RING)
        33184, // Purging staff (BR_PURGING_STAFF)
        33186, // Dragonfire shield (BR_DRAGONFIRE_SHIELD)
        33188, // Twisted buckler (BR_TWISTED_BUCKLER)
        33190, // Masori body (f) (BR_MASORI_BODY_FORTIFIED)
        33192, // Masori chaps (f) (BR_MASORI_CHAPS_FORTIFIED)
        33194, // Torva platelegs (BR_TORVA_LEGS)
        33196, // Virtus robe top (BR_VIRTUS_TOP)
        33198, // Virtus robe bottom (BR_VIRTUS_LEGS)
        33200, // Burning claws (BR_BONE_CLAWS)
        33202, // Aranea boots (BR_ARANEA_BOOTS)
        33460, // Dragon crossbow (BR_XBOWS_CROSSBOW_DRAGON)
        33462, // Oathplate helm (BR_OATHPLATE_HELM)
        33699, // Vial (BR_VIAL_EMPTY)
        34609, // Karil's leatherskirt (BR_BARROWS_KARIL_LEGS)
        34611, // Bandos chestplate (BR_BANDOS_CHESTPLATE)
        34613, // Fighter torso (BR_BARBASSAULT_PENANCE_FIGHTER_TORSO)
        34615, // Black d'hide shield (BR_BLACK_DHIDE_SHIELD)
        34617, // Torva full helm (BR_TORVA_HELM)
        34619, // Abyssal tentacle (BR_ABYSSAL_TENTACLE)
        34621, // Dragon boots (BR_DRAGON_BOOTS)
        34623, // Anglerfish (BR_ANGLERFISH)
        34643 // Supply crate (PVPTUT_COMBO_EATING_SUPPLY_CRATE)
    );

    private ExcludedItemIds() {
    }
}
